version: '3'
services:
  backend:
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./fastapi_service
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ${DATA_FOLDER}:/data

  postgresDB:
    image: postgres
    restart: unless-stopped
    container_name: ${PG_HOST}
    env_file:
      - .env
    ports:
      - 5432:${PG_PORT}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: ${ELASTIC_HOST}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:${ELASTIC_PORT}
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    links:
      - elasticsearch
    ports:
      - 5601:5601
